Bail if the Composer dependencies are not loaded to prevent a fatal
alleyinteractive/wp-alleyvate pull request #30
Opened 2023-05-11 17:13 UTC by srtfisher

Ensure that the plugin does not fatal if Composer is not installed.

2023-05-11 18:51 UTC, dlh01 commented on wp-alleyvate.php
> +}
I'm not sure that I follow this. `load()` is defined in `load.php`, which is included on L38 just below, and which isn't specified as an autoloaded file. How would `load()` exist at this point even under normal circumstances?

2023-05-11 18:55 UTC, srtfisher commented on wp-alleyvate.php
> +}
`load()` would exist if the `vendor/autoload.php` file is required above. if it doesn't exist then we can assume that `vendor/autoload.php` does not exist and we should bail. I didn't write it like this:

```php
if ( file_exists( __DIR__ . '/vendor/autoload.php' ) ) {
	require_once __DIR__ . '/vendor/autoload.php';
} else {
	return;
}
```

because if this plugin is loaded with Composer in a parent project `vendor/autoload.php` will never exist BUT `load()` still can. see a similar check here: https://github.com/alleyinteractive/create-wordpress-plugin/blob/develop/plugin.php#L31-L54

2023-05-11 18:56 UTC, srtfisher commented on wp-alleyvate.php
> +}
Oh I see now, you manually load it. Let me adjust the check to use the Composer autoloader class instead.

2023-05-11 19:06 UTC, srtfisher commented on wp-alleyvate.php
> +}
Took two tries but I think I got it now. @dlh01 what do you think?

2023-05-12 02:31 UTC, dlh01 commented on wp-alleyvate.php
> +}
I was thinking about this more after our first exchange. If we're in a situation where the parent project is loading Composer, all bets are off as to when they're doing that. It might happen after plugins are loaded — who knows? So it seems premature to halt the entire plugin just because Composer wasn't available at the time.

Two other options came to mind:

1. In the `load()` function itself, check whether the `Feature` class exists, and _then_ bail if it doesn't.
2. Same as (1), but instead of bailing, go the extra mile: Have this package include https://github.com/alleyinteractive/wordpress-autoloader as a dependency, and if the classes don't exist by the time `load()` is called, register a custom autoloader so that the plugin can continue.

Thoughts?

2023-05-16 00:32 UTC, srtfisher commented on wp-alleyvate.php
> +}
I think going that far for #2 might be unnecessary. If the plugin's dependencies aren't found in #1 then we should end it right there instead of supporting two solutions or an uncommon edge case. I'll make #1 happen.

2023-05-16 00:36 UTC, srtfisher commented
@dlh01 I went with number 1 -- care for a re-review?

2023-05-16 14:47 UTC, dlh01 requested changes
I agree, (1) is better than (2). Just need to fix the function call.

2023-05-16 14:47 UTC, dlh01 commented on src/alley/wp/alleyvate/load.php
> +	if ( ! class_exists( Feature::class ) ) {
```suggestion
	if ( ! interface_exists( Feature::class ) ) {
```

2023-05-16 14:49 UTC, dlh01 approved these changes
🌳

2023-05-16 14:52 UTC, srtfisher commented on src/alley/wp/alleyvate/load.php
> +	if ( ! class_exists( Feature::class ) ) {
I'm surprised this passed then, TIL.

2023-05-16 14:52 UTC, merged