Feature/7/remove dashboard widgets
alleyinteractive/wp-alleyvate pull request #32
Opened 2023-05-17 15:44 UTC by vancoder

## Summary

As titled.

## Notes for reviewers

None.

## Changelog entries

### Added

### Changed

### Deprecated

### Removed

### Fixed

### Security

2023-05-17 20:51 UTC, attackant approved these changes
Left a comment but looks good.

2023-05-17 20:51 UTC, attackant commented on src/alley/wp/alleyvate/features/class-dashboard-widget-removal.php
> +		return [
Would it make more sense to define the array of widgets as a property?

2023-05-24 16:05 UTC, kevinfodness requested changes
Left some comments related to the tests. Implementation of the feature itself is solid.

2023-05-24 20:54 UTC, vancoder commented on tests/alley/wp/alleyvate/features/test-dashboard-widget-removal.php
> +			);
If the feature has worked, it has removed the specified element from the array - therefore this suggested method gets an `Undefined array key "dashboard_primary"` error. Am I missing something?

2023-07-17 18:06 UTC, kevinfodness approved these changes
🍣

2023-09-19 20:10 UTC, merged