setting up Apple News push feature
alleyinteractive/wp-alleyvate pull request #44
Opened 2023-06-15 16:52 UTC by mogmarsh

## Summary

As titled.

## Notes for reviewers

None.

## Changelog entries

### Added

### Changed

### Deprecated

### Removed

### Fixed

### Security

2023-06-20 12:32 UTC, renatonascalves requested changes
Left a few questions and suggestions. :)

2023-06-20 12:32 UTC, renatonascalves commented on src/alley/wp/alleyvate/features/class-disable-apple-news-no-prod-push.php
> +	 * @var [type]
```suggestion
	 * @var bool
```

2023-06-20 12:32 UTC, renatonascalves commented on src/alley/wp/alleyvate/features/class-disable-apple-news-no-prod-push.php
> +	public function filter_apple_news_skip_push( bool $skip ) {
```suggestion
	public function filter_apple_news_skip_push( bool $skip ): bool {
```

2023-06-20 12:32 UTC, renatonascalves commented on src/alley/wp/alleyvate/features/class-disable-apple-news-no-prod-push.php
> +	public function filter_apple_news_skip_push( bool $skip ) {
Missing phpdoc for `@return`

2023-06-20 12:32 UTC, renatonascalves commented on src/alley/wp/alleyvate/features/class-disable-apple-news-no-prod-push.php
> +		return false;
```suggestion
		return ( \defined( 'VIP_GO_ENV' ) && VIP_GO_ENV === 'production' );
```

2023-08-07 17:06 UTC, mogmarsh commented on src/alley/wp/alleyvate/features/class-disable-apple-news-no-prod-push.php
> +		return apply_filters( 'alleyvate_disable_apple_news_no_prod_push', true );
switching this to being filtered with `alleyvate_load_disable_apple_news_no_prod_push` in load.php

2023-08-07 17:08 UTC, mogmarsh commented on src/alley/wp/alleyvate/load.php
> +		'disable_apple_new_push'        => new Features\Disable_Apple_News_No_Prod_Push(),
went with `disable_apple_news_no_prod_push`

2023-08-09 13:34 UTC, anubisthejackle commented on src/alley/wp/alleyvate/features/class-disable-apple-news-non-prod-push.php
> +		$this->is_production = $this->is_production_environment();
It feels like the only purpose for this class parameter is to make it easier to test the class. If that's not the case, whats the other reason? If that is the case, I'd encourage you to reconsider. Testing is great, but when we have to jump through hoops to make the tests work, that speaks to a likely issue with our architecture.

2023-08-09 13:34 UTC, anubisthejackle commented on src/alley/wp/alleyvate/features/class-disable-apple-news-non-prod-push.php
> +	}
This entire method feels like it has broader applicability than just this class. Could we move this to a helpers file? I think if we do that, we could then use it directly in the method where we're check `if ( $this->is_production ) {` instead, and then in the tests we can mock the helper function.

2023-08-09 21:19 UTC, dlh01 commented on src/alley/wp/alleyvate/features/class-disable-apple-news-non-prod-push.php
> +	 * but it defaults to 'production' if no value is set, which did not seem ideal for this use case.
While a return value of `production` might be unreliable for this reason, is a return value other than `production` still reliable?

2023-11-14 19:12 UTC, jakewrfoster commented
@mogmarsh does this close #26 ?

2023-11-14 22:38 UTC, benpbolton submitted a review, later dismissed
Temporary review

2023-11-15 14:47 UTC, emilyatmobtown commented
I'd recommend also disabling remote images when not on production. Otherwise, Apple News will trigger an error and fail the push if it tries to fetch remote images that it doesn't have access to, i.e. from local envs or protected non-production envs.

2023-11-15 14:49 UTC, mogmarsh commented
> I'd recommend also disabling remote images when not on production. Otherwise, Apple News will trigger an error and fail the push if it tries to fetch remote images that it doesn't have access to, i.e. from local envs or protected non-production envs.

this is disabling all pushes, so the image references won't matter.

2023-11-15 15:00 UTC, emilyatmobtown commented
@mogmarsh Ah, right. I was thinking of scenarios in which we have test credentials on non-prod. 

In that case, I'd suggest also disabling if `WP_CLI` is true. That will ensure that posts don't get pushed on batch updates via CLI in `production`.

2024-07-11 16:34 UTC, jakewrfoster commented
@emilyatmobtown's input is valid, but should come in the form of a future issue and not block this one. I see preventing prod bulk CLI updates as a separate feature from blocking pushes on lower environments.

2024-07-11 19:42 UTC, mogmarsh commented
> @emilyatmobtown's input is valid, but should come in the form of a future issue and not block this one. I see preventing prod bulk CLI updates as a separate feature from blocking pushes on lower environments.

https://github.com/alleyinteractive/wp-bulk-task/blob/main/src/trait-bulk-task-side-effects.php also could handle this in many CLI situations if we use it.

2024-07-16 16:30 UTC, srtfisher approved these changes

2024-07-16 16:30 UTC, srtfisher commented on tests/bootstrap.php
> +\define( 'WP_RUN_CORE_TESTS', true ); // phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedConstantFound
fwiw, mantle will set this: https://github.com/alleyinteractive/mantle-framework/blob/4961ae56da6464d0b4732f075ea8e9ca2b3e2d89/src/mantle/testing/wordpress-bootstrap.php#L106-L108

2024-07-16 16:35 UTC, anubisthejackle commented on tests/bootstrap.php
> +\define( 'WP_RUN_CORE_TESTS', true ); // phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedConstantFound
Interesting. It wasn't, which is why I had to add it here. Maybe worth a look?

2024-07-16 16:35 UTC, anubisthejackle commented on tests/bootstrap.php
> +\define( 'WP_RUN_CORE_TESTS', true ); // phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedConstantFound
Ohhh I missed the `asof` line. That's probably why.

2024-07-16 16:46 UTC, merged