Issue-42: [FEATURE] Disable deep pagination
alleyinteractive/wp-alleyvate pull request #87
Opened 2024-04-09 20:30 UTC by anubisthejackle

## Summary

As titled.

## Notes for reviewers

None.

## Other Information

- [ ] I updated the `README.md` file for any new/updated features.
- [ ] I updated the `CHANGELOG.md` file for any new/updated features.

## Changelog entries

### Added
- Disable pagination past page 100 for frontend and unauthenticated REST requests. Allow customization of the limit. [#42](https://github.com/alleyinteractive/wp-alleyvate/issues/42)

### Changed

### Deprecated

### Removed

### Fixed

### Security

2024-04-10 18:24 UTC, srtfisher requested changes

2024-04-10 18:24 UTC, srtfisher commented on src/alley/wp/alleyvate/features/class-disable-deep-pagination.php
> +		wp_die(
This would be better handled as 404'ing the page instead of showing a `wp_die()`. We should also prevent the next page link (`<link rel="next"`> from linking to a page that will 404.

2024-04-10 18:44 UTC, anubisthejackle commented on src/alley/wp/alleyvate/features/class-disable-deep-pagination.php
> +		wp_die(
Going off the issue, the ask was for a 400. 

> With this status header, it would not impact SEO, there would be no duplicate content issues, etc. We would have to figure out what to render to the client, e.g. an empty page with a message indicating the error? However we implement the response, it will be important to be explicit about why the request failed, so if one of us hits this error there's no mystery to it.

I think the `wp_die()` here makes sense in that case, given we want to stop execution of the page as early as possible. The idea being that we're trying to avoid performance issues from web scrapers.

2024-04-15 16:40 UTC, srtfisher approved these changes

2024-04-15 16:40 UTC, merged